<?php
require_once __DIR__.'/../includes/functions.php'; $u=require_auth(); $title='Dashboard — FluxDrive';
$stats=storage_stats((int)$u['id']); $types=file_type_stats((int)$u['id']);
$st=db()->prepare("SELECT f.*,fo.folder_name FROM files f LEFT JOIN folders fo ON fo.id=f.folder_id WHERE f.user_id=? AND f.is_deleted=0 ORDER BY f.updated_at DESC LIMIT 8");$st->execute([$u['id']]);$recent=$st->fetchAll();
$ac=db()->prepare("SELECT * FROM activities WHERE user_id=? ORDER BY created_at DESC LIMIT 8");$ac->execute([$u['id']]);$acts=$ac->fetchAll();
include __DIR__.'/../includes/header.php'; include __DIR__.'/../includes/sidebar.php'; ?><div class="app-shell"><div class="main"><div class="mobile-spacer"></div><?php include __DIR__.'/../includes/navbar.php';?><section class="page-wrap">
<div class="page-heading"><div><span class="eyebrow">OVERVIEW</span><h1>Welcome back, <?=e($u['full_name'])?></h1><p>Here's what's happening with your storage.</p></div><div class="quick-actions"><button class="btn btn-primary" onclick="openUpload()"><i class="bi bi-cloud-upload"></i> Upload File</button><button class="btn btn-light border" onclick="createFolder()"><i class="bi bi-folder-plus"></i> New Folder</button></div></div>
<div class="stat-grid"><?php $cards=[['Total Storage',human_bytes($stats['total']),'bi-hdd'],['Used Storage',human_bytes($stats['used']),'bi-cloud'],['Free Storage',human_bytes($stats['free']),'bi-database-check'],['Total Files',$stats['files'],'bi-files']];foreach($cards as $c):?><div class="stat-card"><div class="stat-icon"><i class="bi <?=$c[2]?>"></i></div><span><?=$c[0]?></span><strong><?=$c[1]?></strong><?php if($c[0]=='Used Storage'):?><div class="progress mt-2"><div class="progress-bar" style="width:<?=$stats['percent']?>%"></div></div><?php endif;?></div><?php endforeach;?></div>
<div class="content-grid"><div class="panel"><div class="panel-head"><h2>Recent files</h2><a href="files.php">View all</a></div><div class="file-list"><?php if(!$recent):?><div class="empty-state compact"><i class="bi bi-cloud"></i><h3>No files yet</h3><p>Upload your first file to get started.</p></div><?php endif;?><?php foreach($recent as $f):?><div class="file-row"><div class="file-icon"><i class="bi <?=e(icon_for($f['mime_type']))?>"></i></div><div class="file-main"><strong><?=e($f['file_name'])?></strong><small><?=e($f['folder_name']??'My Files')?> · <?=e(human_bytes((int)$f['file_size']))?></small></div><span class="file-date"><?=e(date('M j, Y',strtotime($f['updated_at'])))?></span><button class="icon-btn" onclick="fileMenu(<?=intval($f['id'])?>)"><i class="bi bi-three-dots-vertical"></i></button></div><?php endforeach;?></div></div>
<div class="panel"><div class="panel-head"><h2>Storage</h2><a href="storage.php">Details</a></div><canvas id="storageChart" height="220"></canvas><div class="legend-list"><?php foreach($types as $k=>$v):?><div><span><i class="legend-dot"></i><?=e($k)?></span><b><?=e(human_bytes($v))?></b></div><?php endforeach;?></div></div></div>
<div class="panel mt-4"><div class="panel-head"><h2>Recent activity</h2><span class="muted">Latest actions</span></div><?php if(!$acts):?><div class="empty-state compact"><p>No activity yet.</p></div><?php else:foreach($acts as $a):?><div class="activity-row"><div class="activity-icon"><i class="bi bi-activity"></i></div><div><strong><?=e($a['description'])?></strong><small><?=e(date('M j, Y · g:i A',strtotime($a['created_at'])))?></small></div></div><?php endforeach;endif;?></div>
</section></div></div>
<script>window.storageTypes=<?=json_encode(array_values($types))?>;window.storageLabels=<?=json_encode(array_keys($types))?>;</script><?php $scripts=['/FluxDrive/assets/js/dashboard.js']; include __DIR__.'/../includes/footer.php';?>
