<?php
require_once __DIR__.'/../includes/functions.php'; $u=require_auth(); $title='My Files — FluxDrive'; $folderId=(int)($_GET['folder']??root_folder_id($u['id']));
$st=db()->prepare('SELECT * FROM folders WHERE id=? AND user_id=?');$st->execute([$folderId,$u['id']]);$folder=$st->fetch(); if(!$folder){$folderId=root_folder_id($u['id']);$st=db()->prepare('SELECT * FROM folders WHERE id=? AND user_id=?');$st->execute([$folderId,$u['id']]);$folder=$st->fetch();}
$folders=[];$st=db()->prepare('SELECT * FROM folders WHERE parent_id=? AND user_id=? ORDER BY folder_name');$st->execute([$folderId,$u['id']]);$folders=$st->fetchAll();
$st=db()->prepare('SELECT * FROM files WHERE folder_id=? AND user_id=? AND is_deleted=0 ORDER BY updated_at DESC');$st->execute([$folderId,$u['id']]);$rows=$st->fetchAll();
$crumbs=breadcrumb($folderId,$u['id']); include __DIR__.'/../includes/header.php'; include __DIR__.'/../includes/sidebar.php';?><div class="app-shell"><div class="main"><?php include __DIR__.'/../includes/navbar.php';?><section class="page-wrap"><div class="page-heading"><div><span class="eyebrow">FILE MANAGER</span><h1><?=e($folder['folder_name'])?></h1><div class="breadcrumbs"><a href="files.php">My Files</a><?php foreach($crumbs as $c):?><span>/</span><a href="files.php?folder=<?=$c['id']?>"><?=e($c['folder_name'])?></a><?php endforeach;?></div></div><div class="quick-actions"><button class="btn btn-primary" onclick="openUpload(<?=intval($folderId)?>)"><i class="bi bi-cloud-upload"></i> Upload</button><button class="btn btn-light border" onclick="createFolder(<?=intval($folderId)?>)"><i class="bi bi-folder-plus"></i> Folder</button><div class="btn-group"><button class="btn btn-light border" onclick="setFileView('grid')"><i class="bi bi-grid"></i></button><button class="btn btn-light border" onclick="setFileView('list')"><i class="bi bi-list"></i></button></div></div></div>
<div class="panel"><div class="file-grid" id="fileGrid"><?php foreach($folders as $f):?><div class="file-card folder-card" onclick="location.href='files.php?folder=<?=$f['id']?>'"><div class="file-card-top"><i class="bi bi-folder2 file-folder-icon"></i><button class="icon-btn" onclick="event.stopPropagation();folderMenu(<?=$f['id']?>)"><i class="bi bi-three-dots-vertical"></i></button></div><strong><?=e($f['folder_name'])?></strong><small>Folder</small></div><?php endforeach;?><?php foreach($rows as $f):?><div class="file-card"><div class="file-card-top"><div class="file-icon lg"><i class="bi <?=e(icon_for($f['mime_type']))?>"></i></div><button class="icon-btn" onclick="event.stopPropagation();fileMenu(<?=$f['id']?>)"><i class="bi bi-three-dots-vertical"></i></button></div><strong class="truncate"><?=e($f['file_name'])?></strong><small><?=e(human_bytes((int)$f['file_size']))?> · <?=e(date('M j',strtotime($f['updated_at'])))?></small><button class="starr-btn <?=((int)$f['is_starred']?'active':'')?>" onclick="toggleStar(<?=$f['id']?>);event.stopPropagation()"><i class="bi bi-star<?=((int)$f['is_starred']?'-fill':'')?>"></i></button></div><?php endforeach;?><?php if(!$folders&&!$rows):?><div class="empty-state"><i class="bi bi-folder2-open"></i><h3>No files yet</h3><p>Upload your first file to get started.</p><button class="btn btn-primary" onclick="openUpload(<?=$folderId?>)">Upload File</button></div><?php endif;?></div></div></section></div></div>
<div class="modal fade" id="uploadModal" tabindex="-1"><div class="modal-dialog modal-lg modal-dialog-centered"><div class="modal-content"><div class="modal-header"><h5>Upload files</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div id="dropzone" class="dropzone" onclick="document.getElementById('fileInput').click()"><i class="bi bi-cloud-arrow-up"></i><h4>Drop files here</h4><p>or click to browse</p><input id="fileInput" type="file" multiple hidden></div><div id="uploadQueue" class="mt-3"></div></div></div></div></div>
<?php $scripts=['/FluxDrive/assets/js/files.js']; include __DIR__.'/../includes/footer.php';?>
