<?php
require_once __DIR__.'/../includes/functions.php';
if (current_user()) { header('Location: dashboard.php'); exit; }
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>FluxDrive — Beyond local limits.</title>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
<link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.css" rel="stylesheet">
<link rel="stylesheet" href="../assets/css/style.css"></head><body>
<nav class="landing-nav container"><a class="brand" href="index.php"><span class="brand-mark"><i class="bi bi-cloud-arrow-up"></i></span>FluxDrive</a><div class="d-flex gap-2"><a href="#features" class="btn btn-link">Features</a><a href="login.php" class="btn btn-outline-primary">Login</a><a href="signup.php" class="btn btn-primary">Sign Up</a></div></nav>
<main>
<section class="hero-section container"><div class="hero-copy"><span class="eyebrow">BEYOND LOCAL LIMITS.</span><h1>Your files.<br><span>Anywhere. Anytime.</span></h1><p>Store, manage and access your files securely from anywhere using cloud storage powered by AWS.</p><div class="d-flex gap-3 flex-wrap"><a href="signup.php" class="btn btn-primary btn-lg">Get Started <i class="bi bi-arrow-right"></i></a><a href="login.php" class="btn btn-light btn-lg border">Login</a></div><div class="hero-trust"><span><i class="bi bi-shield-check"></i> Private by default</span><span><i class="bi bi-cloud"></i> Amazon S3</span><span><i class="bi bi-lightning-charge"></i> Fast access</span></div></div><div class="hero-visual"><div class="cloud-art"><div class="cloud-circle c1"></div><div class="cloud-circle c2"></div><div class="cloud-circle c3"></div><div class="cloud-core"><i class="bi bi-cloud-fill"></i><small>FluxDrive</small></div><div class="orbit-card oc1"><i class="bi bi-file-earmark-pdf"></i><span>notes.pdf</span></div><div class="orbit-card oc2"><i class="bi bi-image"></i><span>photo.png</span></div><div class="orbit-card oc3"><i class="bi bi-file-earmark-zip"></i><span>backup.zip</span></div></div></div></section>
<section id="features" class="section container"><div class="section-head"><span class="eyebrow">FEATURES</span><h2>Everything you need to manage your cloud files.</h2></div><div class="feature-grid">
<?php foreach([['shield-lock','Secure Storage'],['cloud-upload','Fast Uploads'],['folder2-open','Easy File Management'],['share','File Sharing'],['pie-chart','Storage Analytics'],['globe2','Access Anywhere']] as $f): ?><div class="feature-card"><div class="feature-icon"><i class="bi bi-<?= $f[0] ?>"></i></div><h3><?= $f[1] ?></h3><p>Built for simple, secure cloud storage workflows.</p></div><?php endforeach; ?></div></section>
<section class="section security-section"><div class="container security-inner"><div><span class="eyebrow">SECURITY</span><h2>Private storage, sensible access.</h2><p>FluxDrive keeps your S3 bucket private and uses short-lived signed URLs for downloads and previews.</p></div><div class="security-pills"><?php foreach(['Amazon S3','Private storage','Encryption','Secure authentication','Access control'] as $x): ?><span><i class="bi bi-check2-circle"></i><?= $x ?></span><?php endforeach; ?></div></div></section>
<section class="section container"><div class="section-head"><span class="eyebrow">HOW IT WORKS</span><h2>Simple from day one.</h2></div><div class="steps"><?php foreach([['1','Create account'],['2','Upload files'],['3','Store securely in AWS'],['4','Access from anywhere']] as $s): ?><div class="step"><b><?= $s[0] ?></b><span><?= $s[1] ?></span></div><?php endforeach; ?></div></section>
</main><footer class="landing-footer container"><span>© <?= date('Y') ?> FluxDrive</span><span>Beyond local limits.</span></footer>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script></body></html>
